spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runoob?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
#    url: jdbc:postgresql://localhost:5432/cloud2003
#    username: cloud2003
#    password: aaaaaa
  security:
    user:
      name: root
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
#    properties:
#      hibernate:
#        default_schema: cloud2003
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
