spring:
  datasource:
    url: jdbc:mysql://localhost:3306/runoob?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
  security:
    user:
      name: root
      password: admin
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace